---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:latest
  # EE_BUILDER_IMAGE: registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8:latest

ansible_config: "ansible.cfg"

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
# additional_build_steps:
#   prepend: |
#     RUN echo This is a pre-install command!
#   append:
#     - RUN echo This is a post-install command!
