---
name: Build CI

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: quay.io
  REGISTRY_USER: scottharwell
  IMAGE_NAME: viewpointe-ee
  RH_REGISTRY: registry.redhat.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_USER }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into destination registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Log into Red Hat registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.RH_REGISTRY }}
          username: ${{ secrets.RH_USERNAME }}
          password: ${{ secrets.RH_PASSWORD }}

      - name: Install ansible-builder
        run: sudo pip3 install ansible-builder

      - name: Create the Containerfile file
        run: ansible-builder create

      - name: Create the Dockerfile file
        run: cp context/Containerfile context/Dockerfile

      - name: Set source platform to amd64 since the containers are not built for arm64
        run: sed -i 's/FROM \$/FROM --platform=linux\/amd64 \$/g' context/Dockerfile

      - name: Build Multiarch Containers
        id: dockerbuild
        uses: docker/build-push-action@v2
        with:
          context: context/.
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
